credentials:
  usernames:
    admin:
      email: admin@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Администратор
      # Внизу зашифрованный пароль "123". Копируйте эту строку целиком!
      password: "$2b$12$1.rIS/fXJj.X/j.X/j.X/j.X/j.X/j.X/j.X/j.X/j.X/j.X/j."
cookie:
  expiry_days: 30
  key: random_signature_key
  name: some_cookie_name
preauthorized:
  emails: []
